version: '3.1'
services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 2367:2368
    volumes:   
      - /home/blog/content:/var/lib/ghost/content
    environment:
      url: "http://****:2368"
      database__client: mysql
      database__connection__host: 172.*.*.*
      database__connection__user: ***
      database__connection__password: *******
      database__connection__database: ghost
  nginx:
    image: nginx
    volumes:
      - /home/blog/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2368:80"
    restart: always
