version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hello

